encoding: UTF-8

profiles:
  production:
    disqus: v4tov6
    google_analytics: UA-5839460-1
    change_frequency: weekly
    base_url: https://www.knowledgebombs.net/
    deploy:
      host: awestruct@oxygen.clearfly.net
      path: /var/www/knowledgebombs.net
      uncommitted: true